apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 803989606864.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-main:5775208963e32bda6a248d16304bb4b6f909df2a
        ports:
        - containerPort: 80

