apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:a9d8700108edb2eede1975a442ab90bc9130d75c
        ports:
        - containerPort: 80
