apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 803989606864.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:5775208963e32bda6a248d16304bb4b6f909df2a
        ports:
        - containerPort: 80
