apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-phones:43365da286b91081812f95ac12096cbd5fd6a003
        ports:
        - containerPort: 80
